apiVersion: v1
kind: ConfigMap
metadata:
  name: connect-configmap
data:
  CONNECT_BOOTSTRAP_SERVERS: 'kafka-service.default.svc.cluster.local:9092'
  CONNECT_REST_ADVERTISED_HOST_NAME: "connect-statefulset-0"
  CONNECT_REST_PORT: "8083"
  CONNECT_GROUP_ID: "compose-connect-group"
  CONNECT_CONFIG_STORAGE_TOPIC: "connect-configs"
  CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
  CONNECT_OFFSET_FLUSH_INTERVAL_MS: "10000"
  CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
  CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
  CONNECT_STATUS_STORAGE_TOPIC: "connect-status"
  CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
  CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
  CONNECT_VALUE_CONVERTER: "io.confluent.connect.avro.AvroConverter"
  CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://schemareg-service.default.svc.cluster.local:8081"
  CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
  CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
  CONNECT_ZOOKEEPER_CONNECT: "zookeeper-service.default.svc.cluster.local:2181"
  CONNECT_PLUGIN_PATH: "/usr/share/plugins,/usr/share/java,/usr/share/confluent-hub-components,/plugins"
  CONNECT_LOG4J_LOGGERS: "org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR"
  #  CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
  KAFKA_HEAP_OPTS: "-Xms256M -Xmx512M"

