apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flink-savepoints-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: topology-aware-standard
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flink-myjars-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: topology-aware-standard
  resources:
    requests:
      storage: 1Gi
