apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-claim-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-claim-log
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
