apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-configmap
data:
  kafka_broker_id: "1"
  kafka_zookeeper_connect: "zookeeper-service.default.svc.cluster.local:2181"
  kafka_listener_security_protocol_map: "PLAINTEXT_IN:PLAINTEXT,PLAINTEXT_OUT:PLAINTEXT"
  kafka_advertised_listeners: "PLAINTEXT_OUT://kafka-service.default.svc.cluster.local:9092,PLAINTEXT_IN://localhost:29092"
  kafka_inter_broker_listener_name: "PLAINTEXT_IN"
  kafka_offsets_topic_replication_factor: "1"
  kafka_group_initial_rebalance_delay_ms: "0"
  kafka_heap_opts: "-Xmx512M -Xms512M"
