apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-statefulset
spec:
  selector:
    matchLabels:
      app: kafka
  replicas: 1
  serviceName: kafka-service
  template:
    metadata:
      labels:
        app: kafka
    spec:
      initContainers:
      - name: volume-clean-lostfound
        image: busybox
        command:
        - sh
        - -c
        - rm -rf /var/lib/kafka/data/lost+found
        securityContext:
          privileged: true
        volumeMounts:
        - name: kafka-volume
          mountPath: /var/lib/kafka/data
      containers:
      - name: kafka-container
        image: confluentinc/cp-kafka:5.4.1
        env:
          - name: KAFKA_BROKER_ID
            valueFrom:
              configMapKeyRef:
                key: kafka_broker_id
                name: kafka-configmap
          - name: KAFKA_ZOOKEEPER_CONNECT
            valueFrom:
              configMapKeyRef:
                key: kafka_zookeeper_connect
                name: kafka-configmap
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            valueFrom:
              configMapKeyRef:
                key: kafka_listener_security_protocol_map
                name: kafka-configmap
          - name: KAFKA_ADVERTISED_LISTENERS
            valueFrom:
              configMapKeyRef:
                key: kafka_advertised_listeners
                name: kafka-configmap
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            valueFrom:
              configMapKeyRef:
                key: kafka_offsets_topic_replication_factor
                name: kafka-configmap
          - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
            valueFrom:
              configMapKeyRef:
                key: kafka_group_initial_rebalance_delay_ms
                name: kafka-configmap
          - name: KAFKA_HEAP_OPTS
            valueFrom:
              configMapKeyRef:
                key: kafka_heap_opts
                name: kafka-configmap
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            valueFrom:
              configMapKeyRef:
                key: kafka_inter_broker_listener_name
                name: kafka-configmap
        ports:
        - containerPort: 9092
          name: kafka-port-out
        - containerPort: 29092
          name: kafka-port-in
        resources:
          requests:
            memory: "300M"
            cpu: "100m"
          limits:
            memory: "2G"
            cpu: "2000m"
        livenessProbe:
          exec:
            command: ['/bin/bash', '-c', 'kafka-consumer-groups --list --bootstrap-server localhost:9092 | head -1']
          initialDelaySeconds: 600
          periodSeconds: 300
          timeoutSeconds: 10
        readinessProbe:
          exec:
            command: ['/bin/bash', '-c', 'kafka-consumer-groups --list --bootstrap-server localhost:9092 | head -1']
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 10
        volumeMounts:
        - name: kafka-volume
          mountPath: /var/lib/kafka/data
      volumes:
      - name: kafka-volume
        persistentVolumeClaim:
          claimName: kafka-claim
