apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: topology-aware-standard
  resources:
    requests:
      storage: 2Gi
